Test_IA : ../../obj/affichage.o ../../obj/mains.o ../../obj/ordinateur.o ../../obj/fonctions_joueur.o ../../obj/fonctions_jeu.o main.o
	gcc -o Test_IA ../../obj/affichage.o ../../obj/mains.o ../../obj/ordinateur.o ../../obj/fonctions_joueur.o ../../obj/fonctions_jeu.o main.o

main.o : main.c ../../src/commun.h ../../src/affichage.h ../../src/ordinateur.h ../../src/fonctions_joueur.h ../../src/fonctions_jeu.h ../../src/mains.h
	gcc -o main.o -c main.c -Wall -O